version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    env_file:
      - .env # Create .env file in root folder and place SA_PASSWORD=<your_strong_password> there.
    ports:
      - '1433:1433'
